#!/bin/bash

for hal in $(cat ./halcs)
do
mkdir M${hal};
cp ./materials_list ./M${hal}/materials_list;
cd M${hal};
for var in $(cat ./materials_list)
do
mkdir ${var}${hal};
cd ${var}${hal};
mkdir 1T;
mkdir 1H;
cd ..;
done
cd ..;
done
