#!/bin/bash

elem=$(cat ./hal)
file="materials_list"

for hal in $(cat ./halcs)
do
cd M${hal};
for var in $(cat ./materials_list)
do
cd ${var}${hal}/mech_1T_U
#echo 200 | vaspkit > mech_1T_U;
cat mech_1T_U | tail -n 68 | head -n 52  > mech_1T
sed -e "s/[[:space:]]\+/ /g" mech_1T > mech
cp mech /home/user/2D_materials/Base/M${hal}/${var}${hal}/1T/mech
cd ..;
cd ..;
cd ${var}${hal}/mech_2H_U
#echo 200 | vaspkit > mech_2H_U;
cat mech_2H_U | tail -n 68 | head -n 52  > mech_1H
sed -e "s/[[:space:]]\+/ /g" mech_1H > mech
cp mech /home/user/2D_materials/Base/M${hal}/${var}${hal}/1H/mech
cd ..;
cd ..;
done
cd ..;
done

