#!/bin/bash

elem=$(cat ./hal)
file="materials_list"

for hal in $(cat ./halcs)
do
cd M${hal};
for var in $(cat ./materials_list)
do
cd ${var}${hal}/static_1T_U
cat OSZICAR | tail -n 1 > en_1T
sed -e "s/[[:space:]]\+/ /g" en_1T > en_m
cp en_m /home/user/2D_materials/Base/M${hal}/${var}${hal}/1T/energy_mag
cd ..;
cd ..;
cd ${var}${hal}/static_2H_U
cat OSZICAR | tail -n 1 > en_1H
sed -e "s/[[:space:]]\+/ /g" en_1H > en_m
cp en_m /home/user/2D_materials/Base/M${hal}/${var}${hal}/1H/energy_mag
cd ..;
cd ..;
done
cd ..;
done

