#!/bin/bash

elem=$(cat ./hal)
file="materials_list"

for hal in $(cat ./halcs)
do
cd M${hal};
for var in $(cat ./materials_list)
do
cd ${var}${hal}/bands_1T_U
echo 911 | vaspkit
cat BAND_GAP | tail -n 14 | head -n 13 > bands
cp bands /home/user/2D_materials/Base/M${hal}/${var}${hal}/1T/
cd ..
cd ..
cd ${var}${hal}/bands_2H_U
echo 911 | vaspkit > b_1H
cat BAND_GAP | tail -n 14 | head -n 13 > bands
cp bands /home/user/2D_materials/Base/M${hal}/${var}${hal}/1H/
cd ..
cd ..
done
cd ..
done

