#!/bin/bash

for hal in $(cat ./halcs)
do
cd M${hal};
for var in $(cat ./materials_list)
do
cd ${var}${hal}/WF_1T_U
(echo 426; echo 3) | vaspkit > WF_1T
cat WF_1T | tail -n 18 | head -n 2 > wf
cp wf /home/user/2D_materials/Base/M${hal}/${var}${hal}/1T/
cd ..
cd ..
cd ${var}${hal}/WF_2H_U
(echo 426; echo 3) | vaspkit > WF_1H
cat WF_1H | tail -n 18 | head -n 2 > wf
cp wf /home/user/2D_materials/Base/M${hal}/${var}${hal}/1H/
cd ..
cd ..
done
cd ..
done

